# Generated by Django 2.0.3 on 2018-05-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your episode', max_length=200)),
                ('story', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='podcasts/episodes/files/')),
                ('avatar', models.ImageField(upload_to='podcasts/episodes/')),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('soundcloud_link', models.URLField(blank=True, help_text='The link to the episode soundcloud')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the podcast', max_length=200, unique=True)),
                ('description', models.CharField(blank=True, help_text='A short description of the podcast', max_length=1000)),
                ('avatar', models.ImageField(null=True, upload_to='podcasts/avatars/')),
                ('itunes_link', models.URLField(blank=True, help_text='The link to your iTunes channel')),
                ('blubrry_link', models.URLField(blank=True, help_text='The link to you Blubrry channel')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
    ]
