# Generated by Django 2.0.3 on 2018-09-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortstories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstory',
            name='body',
            field=models.TextField(default='No story written by the author'),
        ),
    ]
