# Generated by Django 2.0.3 on 2018-09-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortstories', '0002_shortstory_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstory',
            name='minutes_to_read',
            field=models.IntegerField(default=0),
        ),
    ]
